services:
  user:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
